routes:

collections:
  /compliance/state/:
    permalink: /compliance/state/{slug}/
    template: index-lawsummaries
    filter: tag:[compliance,state]
  /compliance/federal/:
    permalink: /compliance/federal/{slug}/
    template: index-lawsummaries
    filter: tag:[compliance,federal]
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
